
PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "/home/zsx/pythonTest/PyFuzzSDE/pyfuzzsde/runner.py", line 153, in trace_dispatch
    sys.settrace(self.trace_dispatch)


PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "/home/zsx/pythonTest/PyFuzzSDE/pyfuzzsde/runner.py", line 153, in trace_dispatch
    sys.settrace(self.trace_dispatch)


PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "/home/zsx/pythonTest/PyFuzzSDE/pyfuzzsde/runner.py", line 257, in run_once
    target(one_input)


PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "/home/zsx/pythonTest/PyFuzzSDE/pyfuzzsde/runner.py", line 153, in trace_dispatch
    sys.settrace(self.trace_dispatch)


PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "/home/zsx/pythonTest/PyFuzzSDE/pyfuzzsde/runner.py", line 153, in trace_dispatch
    sys.settrace(self.trace_dispatch)


PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "/home/zsx/pythonTest/PyFuzzSDE/pyfuzzsde/runner.py", line 153, in trace_dispatch
    sys.settrace(self.trace_dispatch)


PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "/home/zsx/pythonTest/PyFuzzSDE/pyfuzzsde/runner.py", line 153, in trace_dispatch
    sys.settrace(self.trace_dispatch)


PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "/home/zsx/pythonTest/PyFuzzSDE/pyfuzzsde/runner.py", line 153, in trace_dispatch
    sys.settrace(self.trace_dispatch)


PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "/home/zsx/pythonTest/PyFuzzSDE/pyfuzzsde/runner.py", line 153, in trace_dispatch
    sys.settrace(self.trace_dispatch)


PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "/home/zsx/pythonTest/PyFuzzSDE/pyfuzzsde/runner.py", line 153, in trace_dispatch
    sys.settrace(self.trace_dispatch)


PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "/home/zsx/pythonTest/PyFuzzSDE/pyfuzzsde/runner.py", line 153, in trace_dispatch
    sys.settrace(self.trace_dispatch)


PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "/home/zsx/pythonTest/PyFuzzSDE/pyfuzzsde/runner.py", line 153, in trace_dispatch
    sys.settrace(self.trace_dispatch)


PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "/home/zsx/pythonTest/PyFuzzSDE/pyfuzzsde/runner.py", line 153, in trace_dispatch
    sys.settrace(self.trace_dispatch)

